INSERT INTO FinanceDW.Product (
	prodID,
    prodDesc,
    price1,
    price2,
    buID,
    buName,
    buAbbrev,
    unitCost,
    supplierID,
    supplierName,
    supplierAddr1,
    supplierAddr2,
    supplierCity,
    supplierState,
    supplierZip,
	prodTypeID,
	typeDesc)
SELECT prodID,
       prodDesc,
       price1,
       price2,
       buID,
       buName,
       buAbbrev,
       unitCost,
       supplierID,
       supplierName,
       supplierAddr1,
       supplierAddr2,
       supplierCity,
       supplierState,
       supplierZip,
	   prodTypeID,
	   typeDesc
FROM financeDW.Staging
GROUP BY 
	   prodID,
       prodDesc,
       price1,
       price2,
       buID,
       buName,
       buAbbrev,
       unitCost,
       supplierID,
       supplierName,
       supplierAddr1,
       supplierAddr2,
       supplierCity,
       supplierState,
       supplierZip,
	   prodTypeID,
	   typeDesc
;
	
	