INSERT INTO FinanceDW.Staging
(
	custID,
    custName,
    custAddr1,
    custAddr2,
    custCity,
    custState,
    custZip,
    custTypeID,
    custTypeName,
    prodID,
    prodDesc,
    price1,
    price2,
	prodTypeID,
	typeDesc,
    buID,
    buName,
    buAbbrev,
    unitCost,
    supplierID,
    supplierName,
    supplierAddr1,
    supplierAddr2,
    supplierCity,
    supplierState,
    supplierZip,
    invoiceID,
    quantity,
    salesAmount,
    salesDate,
	discounted,
	division,
	costAmount
)
SELECT c.customerID,
	c.name,
    c.addr1,
    c.addr2,
    c.city,
    c.state,
    c.zip,
    c.custTypeID,
    ct.typeName,
    p.prodID,
    p.description,
    p.price1,
    p.price2,
	pt.prodTypeID,
	pt.typeDescription,
    b.BUID,
    b.name,
    b.abbrev,
    p.unitCost,
    s.supplierID,
    s.name,
    s.addr1,
    s.addr2,
    s.city,
    s.state,
    s.zip,
    i.invoiceID,
    i.qty,
    i.amt,
    ih.saleDate,
	i.discounted,
	'TPCE',
	p.unitCost*i.qty
FROM SalesOrders.InvoiceDtl i 
	JOIN SalesOrders.Product p USING(prodID)
	JOIN SalesOrders.InvoiceHdr ih USING(invoiceID)
    JOIN SalesOrders.Customer c USING(customerID)
    JOIN SalesOrders.CustomerType ct USING(custTypeID)
    JOIN SalesOrders.ProdType pt USING(prodTypeID)
    JOIN SalesOrders.BusinessUnit b USING(BUID)
    JOIN SalesOrders.Supplier s USING(supplierID)
GROUP BY
	c.customerID,
	c.name,
    c.addr1,
    c.addr2,
    c.city,
    c.state,
    c.custTypeID,
    ct.typeName,
    p.prodID,
    p.description,
    p.price1,
    p.price2,
	pt.prodTypeID,
	pt.typeDescription,
    b.BUID,
    b.name,
    b.abbrev,
    p.unitCost,
    s.supplierID,
    s.name,
    s.addr1,
    s.addr2,
    s.city,
    s.state,
    s.zip,
    i.invoiceID,
    i.qty,
    i.amt,
    ih.saleDate,
	i.discounted
;
    
    
